### ISSUE TITLE
Verifica esistenza simbolo

### ISSUE THREAD

**Issue by dade80vr** [vittominacori/coinmarketcap-php#1]
Ciao Vittorio, ottimo lavoro, proprio quello che cercavo.
Avrei bisogno di un consiglio/aiuto: ho integrato la tua classe in uno script automatico che cerca vari simboli su alcuni wallet.

Come posso beccare l'errore 400 se il simbolo non è presente su CMC?
Un esempio:
`$response=$cmc->cryptocurrency()->quotesLatest(['symbol' => 'EOP']);`

Ricevo questo output che vorrei evitare:
`Uncaught Exception: Invalid value for "symbol": "EOP"`

Grazie per eventuali consigli.

**Comment by vittominacori** [comment]
Ciao @dade80vr, basta un semplice try/catch e puoi intercettare tutti i tipi di errore.

Ad esempio per il 400 potresti fare qualcosa del genere

```
try {
    $response = $cmc->cryptocurrency()->quotesLatest(['symbol' => 'EOP']);
} catch (\Exception $e) {
    if ($e->getCode() === 400) {
        // do your stuff
        echo $e->getMessage();
    }
}
```

**Comment by dade80vr** [comment]
Giusto, hai ragione.
Grazie mille
