### ISSUE TITLE
src/lib/Utils/ApiRequest.php

### ISSUE THREAD

**Issue by kerenbir** [vittominacori/coinmarketcap-php#2]
can you check line 45.

**Comment by vittominacori** [comment]
What's the issue?

It throws Exception if CMC returns a code different from 200.

You can handle it by using a try/catch like in this [sample](https://github.com/vittominacori/coinmarketcap-php/blob/master/sample.php#L8).

**Comment by kerenbir** [comment]
i build a telegram bot and when i enter the wrong command in telegram i need to wait for about 24 hours again to make bot normal again. and when i check error log i found that line in problem. i dont know why.

**Comment by vittominacori** [comment]
Publish log to understand. 

Anyway try to use it with try/catch as in sample code.

**Comment by kerenbir** [comment]
thank you
